version: '2'

services:
 web:
  image: nginx
  container_name: proxy
  hostname: proxy
  volumes:
   - ./_nginx/proxy.conf:/etc/nginx/proxy.conf:ro
   - ./_nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  ports:
   - "9999:80"
  environment:
   - NGINX_HOST=proxy
   - NGINX_PORT=80
  command: [nginx, '-g', 'daemon off;']

 minio1:
  image: minio/minio
  container_name: minio1
  hostname: minio1
  volumes:
   - data1:/data
  environment:
   MINIO_ACCESS_KEY: minio
   MINIO_SECRET_KEY: minio123
  command: server http://minio1/data http://minio2/data http://minio3/data http://minio4/data

 minio2:
  image: minio/minio
  container_name: minio2
  hostname: minio2
  volumes:
   - data2:/data
  environment:
   MINIO_ACCESS_KEY: minio
   MINIO_SECRET_KEY: minio123
  command: server http://minio1/data http://minio2/data http://minio3/data http://minio4/data

 minio3:
  image: minio/minio
  container_name: minio3
  hostname: minio3
  volumes:
   - data3:/data
  environment:
   MINIO_ACCESS_KEY: minio
   MINIO_SECRET_KEY: minio123
  command: server http://minio1/data http://minio2/data http://minio3/data http://minio4/data

 minio4:
  image: minio/minio
  container_name: minio4
  hostname: minio4
  volumes:
   - data4:/data
  environment:
   MINIO_ACCESS_KEY: minio
   MINIO_SECRET_KEY: minio123
  command: server http://minio1/data http://minio2/data http://minio3/data http://minio4/data

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  data1:
  data2:
  data3:
  data4: